name: PlayPen

#on: workflow_dispatch
on:
  push:
#    branches: [ release/* ]

env:
  pkg-assembly: 'rotatorcontrol.jar'
  pkg-name: 'rotatorcontrol'
  pkg-version: '1.0.1'
  gh-version: 'v1.0.1'
  pkg-mainclass: "com.wa9nnn.rotator.RotatorControl"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

jobs:
  fat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version from file
        id: relVersion
        run: |
          ls
          echo "eVversion=$(cat version.sbt)" >> $GITHUB_OUTPUT

      - name: show version from step
        run: echo b4 ${{steps.relVersion.outputs.eVversion}} after
#        run: echo "step: ${{steps.version.output}}"

      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

    outputs:
      fatOutput: ${{steps.relVersion.output.text}}


  xyzzy:
    needs: fat
    runs-on: ubuntu-latest
    steps:
      - name: look at version
        run: |
          echo b4 ${{needs.fat.output.fatOutput}} after

      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1