name: Build for Release

on: workflow_dispatch
#on:
#  push:
#    branches: [ release/* ]

env:
  pkg-assembly: 'rotatorcontrol.jar'
  pkg-name: 'rotatorcontrol'
  pkg-version: '1.0.1'
  pkg-mainclass: "com.wa9nnn.rotator.RotatorControl"

jobs:
  fat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 14
      - name: Build fat jar
        run: sbt assembly
      - name: Upload fat jar
        uses: actions/upload-artifact@v1
        with:
          name: jars
          path: "target/scala-2.13/${{ env.pkg-assembly }}"
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions environment variables on Windows
        run: env

  github-actions-environment-variables-windows:
    runs-on: windows-latest
    steps:
      - name: Ubuntu GitHub Actions environment variables List
        run: env

  github-actions-environment-variables-macos:
    runs-on: macos-latest
    steps:
      - name: MacOs List of GitHub Actions environment variables
        run: env
  windows:
    needs: fat
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '17'
          java-package: jdk+fx
          architecture: x64
      - name: Download fat jar
        uses: actions/download-artifact@v1
        with:
          name: jars
      - name: Package jar as msi
        run: "jpackage --name ${{ env.pkg-name }} -i jars --main-class ${{env.pkg-mainclass}} --main-jar ${{ env.pkg-assembly }} --win-dir-chooser"
      - name: View artifacts
        run: dir
      - name: Upload installer
        uses: actions/upload-artifact@v1
        with:
          name: msis
          path: "${{ env.pkg-name }}-${{ env.pkg-version }}.msi"
  osx:
    needs: fat
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '17'
          java-package: jdk+fx
          architecture: x64
      - name: Download fat jar
        uses: actions/download-artifact@v1
        with:
          name: jars
      - name: Package jar as dmg installer
        run: "jpackage --name ${{ env.pkg-name }} -i jars --main-class ${{env.pkg-mainclass}} --app-version ${{env.pkg-version}} --main-jar ${{ env.pkg-assembly }} --verbose"
      - name: Upload dmg
        uses: actions/upload-artifact@v1
        with:
          name: dmgs
          path: "${{ env.pkg-name }}-${{ env.pkg-version }}.dmg"
#  linux:
#    needs: fat
#    runs-on: [ubuntu-latest]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#          java-package: jdk
#          architecture: x64
#      - name: Download fat jar
#        uses: actions/download-artifact@v1
#        with:
#          name: jars
#      - name: Package jar as debian package
#        run: "jpackage --name ${{ env.pkg-name }} -i jars --main-class ${{env.pkg-mainclass}} --app-version ${{env.pkg-version}} --main-jar ${{ env.pkg-assembly }} --verbose"
#
#      - name: Upload deb
#        uses: actions/upload-artifact@v1
#        with:
#          name: debs
#          path: "${{ env.pkg-name }}-${{ env.pkg-version }}.deb"
