# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI2

on: workflow_dispatch
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Generate Changelog
          run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
          #    - name: Run tests
          #        run: sbt test
          # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
          #    - name: Upload dependency graph
          #      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
      - name: Build snapshot release
        run: sbt universal:packageBin

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          tag_name: sometagname
          files: target/universal/rotatorcontrol-1.0.0-SNAPSHOT.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
