# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on: workflow_dispatch
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "version.sbt"

      - name: File contents
        run: echo "${ steps.read_file.outputs.contents }"

      - name: "Read file contents"
        id: versionSbt
        uses: andstor/file-reader-action@v1
        with:
          path: "version.sbt"
      - name: File outputs
        run: echo "${ steps.versionSbt.outputs.contents }"
      - name: Generate Changelog
        run:  echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Build snapshot release
        run: sbt universal:packageBin
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          name: tbd
          files: target/universal/rotatorcontrol-1.0.0-SNAPSHOT.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
