# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on: workflow_dispatch
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.sbt
      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"
      - name: parse
        uses: actions-ecosystem/action-regex-match@v2
         with:
          text:${{ steps.package.outputs.content }}
          regex: '.*\"(.*)\"'
      - name: Echo parsed version
          run: echo "${{ steps.package.outputs.group1 }}"



      - name: Generate Changelog
        run:  echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Build snapshot release
        run: sbt universal:packageBin
